---
version: 2
jobs:
  build_deploy:
    docker:
      - image: circleci/node:10.12.0

    steps:
      - checkout: #check out the source code from the repository
          path: /home/circleci/project/serverless/

      - run:
          name: npm installation and check directory
          command: |
            cd /home/circleci/project/serverless/
            npm install
            pwd

      - run:
          name: remove node_modules
          command: |
            cd /home/circleci/project/serverless/
            rm -rf node_modules/

      - run:
          name: Install aws cli and configure
          command: |
            sudo apt-get update && sudo apt-get install python-pip
            sudo pip install awscli
            sudo aws --version
            aws configure set aws_access_key_id ${aws_access_key}
            aws configure set aws_secret_access_key ${aws_secret_key}
            aws configure set region us-east-1
            aws configure list
            pwd
            ls -al
            cd serverless
            zip -r lambdaFunction.zip appspec.yml index.js AWSConfiguration/
            aws s3 cp lambdaFunction.zip s3://${code_deploy_bucket} --region ${aws_region}
            echo "Hello"

workflows:
  version: 2
  build_deploy:
    jobs:
    - build_deploy:
        filters:
            branches:
              only:
                - master
  